# Generated by Django 4.1.4 on 2023-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181001_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(4, 'Komedia'), (3, 'Drama'), (1, 'Horror'), (0, 'Nieznany'), (2, 'Sci-fi')], default=0),
        ),
    ]
